---
- name: playbook for simple 2GB filesystem Creation
  hosts: all
  become: true
  tasks:
    - include_vars:
        file: variable.yaml

    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: task for creating volume group
      lvg:
          vg: "{{vg_name}}"
          pvs: "{{pv}}"
          pesize: 16

    - name: task for creating logical volume
      lvol:
          vg: "{{vg_name}}"
          lv:  mount_lv
          size: "{{extend_size}}"
          force: yes

    - name: Create directory mountpoint if does not exist
      file:
        path: "/mount"
        state: directory
        mode: '0777'

    - name: format the xfs filesystem
      filesystem:
        fstype: "mkfs.xfs"
        dev: /dev/mount_vg/mount_lv

    - name: mount the lv on /mountpoint
      mount:
        path: "/mount"
        src: /dev/mount_vg/mount_lv
        fstype: "mkfs.xfs"
        state: mounted
